export const sportsData = {
  Football: {
    name: "Football",
    icon: "⚽",
    description: "Premier League Football matches across Rwanda",
    teams: [
      "APR FC",
      "Rayon Sports",
      "Police FC",
      "Mukura VS",
      "AS Kigali",
      "SC Kiyovu",
      "Gasogi United",
      "Musanze FC",
    ],
  },
  Basketball: {
    name: "Basketball",
    icon: "🏀",
    description: "Professional Basketball League games",
    teams: ["REG BBC", "Patriots BBC", "Espoir BBC", "APR BBC", "IPRC-South BBC", "UGB BBC"],
  },
  Volleyball: {
    name: "Volleyball",
    icon: "🏐",
    description: "National Volleyball Championship",
    teams: ["Gisagara VC", "UTB VC", "REG VC", "Police VC", "APR VC", "RRA VC"],
  },
  Events: {
    name: "Events",
    icon: "🎪",
    description: "Cultural events, concerts and special occasions",
    teams: [
      "Kigali Music Fest",
      "Youth Sports Day",
      "Cultural Festival",
      "Tech Conference",
      "Art Exhibition",
      "Food Festival",
    ],
  },
}

export const matches = [
  {
    id: 1,
    sport: "Football",
    home_team: "APR FC",
    away_team: "Rayon Sports",
    date: "2025-01-20",
    time: "15:00",
    location: "Kigali Stadium",
    price: 3000,
    vip_price: 8000,
    image: "/football-match-stadium.png",
    status: "upcoming",
    league: "Rwanda Premier League",
  },
  {
    id: 2,
    sport: "Basketball",
    home_team: "REG BBC",
    away_team: "Patriots BBC",
    date: "2025-01-22",
    time: "18:00",
    location: "Amahoro Arena",
    price: 2000,
    vip_price: 5000,
    image: "/indoor-basketball-arena.png",
    status: "upcoming",
    league: "Basketball National League",
  },
  {
    id: 3,
    sport: "Football",
    home_team: "Police FC",
    away_team: "AS Kigali",
    date: "2025-01-25",
    time: "16:00",
    location: "Nyamirambo Stadium",
    price: 2500,
    vip_price: 6000,
    image: "/football-stadium-crowd.png",
    status: "upcoming",
    league: "Rwanda Premier League",
  },
  {
    id: 4,
    sport: "Volleyball",
    home_team: "Gisagara VC",
    away_team: "UTB VC",
    date: "2025-01-27",
    time: "14:00",
    location: "Gisagara Sports Center",
    price: 1500,
    vip_price: 3500,
    image: "/volleyball-court-indoor.jpg",
    status: "upcoming",
    league: "National Volleyball Championship",
  },
  {
    id: 5,
    sport: "Events",
    home_team: "Kigali Music Fest",
    away_team: "",
    date: "2025-02-01",
    time: "19:00",
    location: "BK Arena",
    price: 5000,
    vip_price: 15000,
    image: "/music-concert-stage-lights.jpg",
    status: "upcoming",
    league: "Cultural Events",
  },
  {
    id: 6,
    sport: "Football",
    home_team: "Mukura VS",
    away_team: "SC Kiyovu",
    date: "2025-01-28",
    time: "15:30",
    location: "Huye Stadium",
    price: 2800,
    vip_price: 7000,
    image: "/football-match-stadium.png",
    status: "upcoming",
    league: "Rwanda Premier League",
  },
]

export const userTickets = [
  {
    id: "TKT001",
    match: matches[0],
    quantity: 2,
    total: 6000,
    qr_code: "QR123456789",
    purchase_date: "2025-01-15",
    status: "active",
    seat_numbers: ["A12", "A13"],
    ticket_type: "Regular",
  },
  {
    id: "TKT002",
    match: matches[1],
    quantity: 1,
    total: 2000,
    qr_code: "QR987654321",
    purchase_date: "2025-01-16",
    status: "active",
    seat_numbers: ["B05"],
    ticket_type: "Regular",
  },
]

export const storeProducts = [
  {
    id: 1,
    name: "APR FC Official Jersey",
    price: 25000,
    category: "Jerseys",
    team: "APR FC",
    image: "/jersey-apr.jpg",
    description: "Official home jersey for APR FC",
    sizes: ["S", "M", "L", "XL"],
    stock: 50,
  },
  {
    id: 2,
    name: "Rayon Sports Scarf",
    price: 8000,
    category: "Accessories",
    team: "Rayon Sports",
    image: "/scarf-rayon.jpg",
    description: "Official team scarf",
    stock: 30,
  },
  {
    id: 3,
    name: "Rwanda Football",
    price: 15000,
    category: "Equipment",
    team: "General",
    image: "/football-ball.jpg",
    description: "Official match football",
    stock: 25,
  },
  {
    id: 4,
    name: "REG BBC Basketball Jersey",
    price: 22000,
    category: "Jerseys",
    team: "REG BBC",
    image: "/jersey-reg.jpg",
    description: "Official basketball jersey",
    sizes: ["S", "M", "L", "XL"],
    stock: 40,
  },
]

export const walletTransactions = [
  {
    id: 1,
    type: "deposit",
    amount: 50000,
    description: "Mobile Money Deposit",
    date: "2025-01-15",
    status: "completed",
  },
  {
    id: 2,
    type: "purchase",
    amount: -6000,
    description: "Ticket Purchase - APR FC vs Rayon Sports",
    date: "2025-01-15",
    status: "completed",
  },
  {
    id: 3,
    type: "donation",
    amount: -10000,
    description: "Donation to APR FC",
    date: "2025-01-16",
    status: "completed",
  },
]

export const teams = [
  {
    id: 1,
    name: "APR FC",
    sport: "Football",
    league: "Rwanda Premier League",
    founded: "1993",
    members: 25000,
    description: "One of Rwanda's most successful football clubs with multiple league titles.",
  },
  {
    id: 2,
    name: "Rayon Sports",
    sport: "Football",
    league: "Rwanda Premier League",
    founded: "1968",
    members: 18000,
    description: "Historic football club known for their passionate fanbase and competitive spirit.",
  },
  {
    id: 3,
    name: "REG BBC",
    sport: "Basketball",
    league: "Basketball National League",
    founded: "2015",
    members: 8000,
    description: "Professional basketball club competing at the highest level in Rwanda.",
  },
  {
    id: 4,
    name: "Patriots BBC",
    sport: "Basketball",
    league: "Basketball National League",
    founded: "2013",
    members: 6500,
    description: "Dynamic basketball team with a strong youth development program.",
  },
  {
    id: 5,
    name: "Police FC",
    sport: "Football",
    league: "Rwanda Premier League",
    founded: "1974",
    members: 12000,
    description: "Football club representing the Rwanda National Police with disciplined play.",
  },
  {
    id: 6,
    name: "Gisagara VC",
    sport: "Volleyball",
    league: "National Volleyball Championship",
    founded: "2010",
    members: 3500,
    description: "Leading volleyball club from the Southern Province of Rwanda.",
  },
]
